# Generated by Django 5.1.5 on 2025-02-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='company_name',
        ),
    ]
